### ISSUE TITLE
Compute the accuarcy!

### ISSUE THREAD

**Issue by hzwfl2** [hbdat/cvpr20_DAZLE#3]
I think this is a very valuable work. However, I found you use the `per_class_accuracies.mean().item()` and `acc_per_class.mean().item()` to computer the accuracy of `seen_classes` and `unseen_classes` in the code. As far as I know, the number of samples in each class is not the same. In this condition, use the mean of each class to compute the whole average accuracy seems to unreasonable. So, I want to know why you do that. Thank you!

**Comment by hbdat** [comment]
As mentioned the Evaluation Metric Section, we follow the setting of "Zero-shot learning — the good, the bad and the ugly" CVPR17 to compute per class accuracy, which computes the mean of accuracy in each classes. More details can be found in equation (21) of the paper journal version https://arxiv.org/pdf/1707.00600.pdf .

The main purpose of this setting is to have a fair comparison with results reported by other methods.
Moreover, we believe that per class accuracy reflexes the performance better since the model has to perform well on all classes to achieve high score. 
On the other hand, overall accuracy, which measures average accuracy on samples, can be achieved high values when assigning test samples into classes with the most samples without recognizing other classes.

**Comment by hzwfl2** [comment]
Got it. I will cite your work. Thank you very much for your prompt reply!
